name: Update RPMs and Upload to SourceForge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC

jobs:
  update-and-upload:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf update -y
          dnf install -y createrepo_c jq curl rpm-build rpmdevtools lftp tar gzip sshpass

      - name: Run update script
        run: |
          bash scripts/update_rpm.sh

      - name: Upload RPMs x86_64 and repodata to SourceForge via SFTP
        env:
          SF_SFTP_USER: ${{ secrets.SF_SFTP_USER }}
          SF_SFTP_PASS: ${{ secrets.SF_SFTP_PASS }}
        run: |
          sshpass -p "$SF_SFTP_PASS" scp -r rpm/x86_64 albersonmiranda@frs.sourceforge.net:/home/frs/project/r-tools-ppa/rpm_x86_64

      - name: Upload RPMs aarch64 and repodata to SourceForge via SFTP
        env:
          SF_SFTP_USER: ${{ secrets.SF_SFTP_USER }}
          SF_SFTP_PASS: ${{ secrets.SF_SFTP_PASS }}
        run: |
          sshpass -p "$SF_SFTP_PASS" scp -r rpm/aarch64 albersonmiranda@frs.sourceforge.net:/home/frs/project/r-tools-ppa/rpm_aarch64